OscDrinkOrderBundle_product:
    pattern:  /order
    defaults: { _controller: OscDrinkOrderBundle:DrinkOrder:product }
    requirements: { _method: GET }

OscDrinkOrderBundle_product_post:
    pattern:  /order
    defaults: { _controller: OscDrinkOrderBundle:DrinkOrder:productPost }
    requirements: { _method: POST }

OscDrinkOrderBundle_address:
    pattern:  /order/address
    defaults: { _controller: OscDrinkOrderBundle:DrinkOrder:address }
    requirements: { _method: GET }

OscDrinkOrderBundle_address_post:
    pattern:  /order/address
    defaults: { _controller: OscDrinkOrderBundle:DrinkOrder:addressPost }
    requirements: { _method: POST }

OscDrinkOrderBundle_confirmation:
    pattern:  /order/confirmation
    defaults: { _controller: OscDrinkOrderBundle:DrinkOrder:confirmation }
    requirements: { _method: GET }

OscDrinkOrderBundle_confirmation_post:
    pattern:  /order/confirmation
    defaults: { _controller: OscDrinkOrderBundle:DrinkOrder:confirmationPost }
    requirements: { _method: POST }
