Osc\Bundle\DrinkOrderBundle\Entity\DrinkOrder:
  properties:
    product_id:
      - NotBlank: { groups: [product] }
      - Min: { limit: 1, groups: [product] }
      - Max: { limit: 2, groups: [product] }
    quantity:
      - NotBlank: { groups: [product] }
      - Min: { limit: 1, groups: [product] }
      - Max: { limit: 8, groups: [product] }
    name: &text
      - NotBlank: { groups: [address] }
      - MaxLength: { limit: 16, groups: [address] }
    address: *text
    phone: *text
